
services:
  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "3001:3001"
    volumes:
      - bargainbuddy-data:/app/data
    environment:
      - NODE_ENV=production
      # Add other environment variables if needed

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables if needed

volumes:
  bargainbuddy-data: