name: Test Frontend

on: [push, pull_request]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run frontend in the background
      run: |
        npm run dev > output.log 2>&1 &
      working-directory: ./frontend

    - name: Wait for a few seconds to let the server start
      run: sleep 10

    - name: Wait for frontend to start
      run: |
        for i in {1..5}; do
          if curl -s http://localhost:3000/; then
            echo "Front is running good"
            exit 0
          fi
          echo "Waiting for frontend..."
          sleep 5
        done
        echo "Frontend did not start in time"
        exit 1
      working-directory: ./frontend