name: Test Backend

on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run backend and capture output
      id: run-backend
      run: |
        npm run dev > output.log 2>&1 || true
      working-directory: ./backend

    - name: Check for 'app crashed' error
      run: |
        if grep -q "app crashed" ./backend/output.log; then
          echo "Error: app crashed"
          exit 1
        else
          echo "No 'app crashed' errors found"
        fi
      working-directory: ./backend